default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: suzukagpt_development

test:
  <<: *default
  database: suzukagpt_test