source "https://rubygems.org"

gem "rails", "~> 7.2.1"
gem 'pg', '~> 1.5', '>= 1.5.8'
gem "puma", ">= 5.0"
gem 'pgvector', '~> 0.3.2'
gem 'faraday', '~> 2.0'
gem 'httparty'
gem 'dotenv-rails', '~> 3.1.4'
gem 'rack-cors'
gem 'neighbor'
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end
